name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

env:
  RELEASE_MODE: ReleaseSmall

permissions:
  id-token: 'write'
  attestations: 'write'
  contents: 'write'

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-24.04-arm
          - windows-latest
          - windows-11-arm
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: mlugg/setup-zig@d1434d08867e3ee9daa34448df10607b98908d29  # v2.2.1
        with:
          version: 0.14.0
      - name: Install Dependencies (scoop)
        if: startsWith(matrix.os, 'windows')
        uses: MinoruSekine/setup-scoop@894de8858093e82e95b5f9d13ba907e90d16e954  # v4.0.2
        with:
          apps: >-
            minisign
            zip
      - name: Install Dependencies (brew)
        if: startsWith(matrix.os, 'macos')
        run: brew install minisign
      - name: Install Dependencies (apt)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install minisign
      - name: Run Tests (Debug)
        run: zig build test --summary all
      - name: Build (Debug)
        run: zig build
      - name: Test Build (Debug)
        shell: bash
        run: ./test/test.sh
      - name: Store Debug Build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PopUpdater-${{ runner.os }}-${{ runner.arch }}-Debug
          if-no-files-found: error
          compression-level: 9
          path: |
            zig-out/bin/*
      - name: Run Tests (Release)
        run: zig build test -Doptimize="${{ env.RELEASE_MODE }}" --summary all
      - name: Build (Release)
        run: zig build -Doptimize="${{ env.RELEASE_MODE }}"
      - name: Test Build (Release)
        shell: bash
        run: ./test/test.sh
      - name: Cleanup
        shell: bash
        run: rm -f zig-out/bin/*.pdb
      - name: Package
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')) }}
        shell: bash
        run: |
          mkdir dist
          Z="$(which 7z 2>/dev/null || which 7za 2>/dev/null)"
          "$Z" a -mx=9 -tzip "dist/PopUpdater_${{ github.ref_name }}_${{ runner.os }}-${{ runner.arch }}.zip" ./zig-out/bin/*
      - name: Attest Build
        if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v')) }}
        uses: actions/attest@v4.1.0
        with:
          subject-path: |
            zig-out/bin/*
            dist/*
      - name: Store Release Build
        uses: actions/upload-artifact@v7.0.1
        with:
          name: PopUpdater-${{ runner.os }}-${{ runner.arch }}
          if-no-files-found: error
          compression-level: 9
          path: |
            zig-out/bin/*
      - name: Create Release
        if: ${{ github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags/v') }}
        uses: softprops/action-gh-release@975c1b265e11dd76618af1c374e7981f9a6ff44a
        with:
          draft: true
          prerelease: false
          name: PopUpdater ${{ github.ref_name }}
          fail_on_unmatched_files: true
          files: |
            dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
