name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5.0.0
      - uses: mlugg/setup-zig@v2.0.5
        with:
          version: 0.14.0
      - name: Install Dependencies (scoop)
        if: startsWith(matrix.os, 'windows')
        uses: MinoruSekine/setup-scoop@v4.0.2
        with:
          apps: >-
            minisign
            zip
      - name: Install Dependencies (brew)
        if: startsWith(matrix.os, 'macos')
        run: brew install minisign
      - name: Install Dependencies (apt)
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt install minisign
      - name: Run Tests
        run: zig build test --summary all
      - name: Debug Build
        run: zig build
      - name: Test Debug Build
        shell: bash
        run: ./test/test.sh
      - name: Release Build
        run: zig build -Doptimize=ReleaseSmall
      - name: Test Release Build
        shell: bash
        run: ./test/test.sh
      - name: Store release build
        uses: actions/upload-artifact@v5.0.0
        with:
          name: PopUpdater-${{ runner.os }}-${{ runner.arch }}
          if-no-files-found: error
          compression-level: 9
          path: |
            zig-out/bin/*
            !zig-out/bin/*.pdb
